### Python code to read a CSV generated by Toggl and provide summary statistics (and maybe plots)

# Pandas provides methods for handling CSV files
import pandas as pd

# Read a CSV file into a DataFrame
df = pd.read_csv('TogglTrack_test_2024.csv')

# Show first few lines of CSV
print(df.head())

# Show column names
print(list(df.columns))

# Show tags 
print(df.Tags)

# The Tags column can have multiple entires separated by a comma.  I want to get time information for individual tags.
# Try exploding tags into their own row
# HOWEVER, explode only works on lists, so convert the Tags field to a list

# Convert Duration to timedelta
df['Duration'] = pd.to_timedelta(df['Duration'])

# Convert the Tags column from string to list
# lambda represents an anonymous function
df['Tags'] = df['Tags'].apply(lambda x: [tag.strip() for tag in str(x).split(',')])

df_exploded = df.explode('Tags')

print(f"Length of df {len(df)}")
print(f"Length of df_exploded {len(df_exploded)}")

# Look through each line of df_exploded
# iterows reterns a tuple, so they need unpacking, which can be done using index
for index, row in df_exploded.iterrows():
    print(f"Index: {index} Tags: {row['Tags']} Duration: {row['Duration']}")

# Group by tag and sum durations
tag_duration_sum = df_exploded.groupby('Tags')['Duration'].sum()

# Display result
print(tag_duration_sum)


#Need to convert '1 days 05:18:11' to total hours.
# possibly https://stackoverflow.com/questions/31283001/get-total-number-of-hours-from-a-pandas-timedelta
